sudo: required

language: ruby

services:
  - docker

install:
  - sudo apt-get update -qq
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.9.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - sudo /etc/init.d/mysql stop

script:
  - cp docker-env.dist docker-env
  - docker-compose up -d
  - docker images
  - docker ps
  - docker-compose logs
