version: "3"

services:
  php:
    build: php
    env_file: docker-env
    ports:
      - "9000:9000"
    volumes:
      - "~/www:/var/www/html:delegated"
    tty: true

  nginx:
    build: nginx
    env_file: docker-env
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - "~/www:/var/www/html:delegated"
    tty: true

  mysql:
    image: mariadb:latest
    env_file: docker-env
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    tty: true

  elasticsearch:
    image: elasticsearch:2
    env_file: docker-env
    ports:
      - "9200:9200"
    tty: true

  redis:
    image: redis:latest
    env_file: docker-env
    ports:
      - "6379:6379"
    tty: true

  varnish:
    build: varnish
    env_file: docker-env
    depends_on:
      - nginx
    ports:
      - "80:8080"
    tty: true

  blackfire:
    image: blackfire/blackfire
    env_file: docker-env
    depends_on:
      - php
    ports:
      - "8707:8707"

  maildev:
    image: djfarrelly/maildev
    env_file: docker-env
    depends_on:
      - php
    ports:
      - "1080:80"

volumes:
  mysql: {}
