version: "3.4"

services:
  blackfire:
    image: blackfire/blackfire
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    depends_on:
      - php

  elasticsearch:
    build: elasticsearch
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  maildev:
    image: djfarrelly/maildev
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    depends_on:
      - php
    ports:
      - 1080:80

  mysql:
    image: mysql:5.7
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    tty: true

  nginx:
    build: nginx
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    ports:
      - 443:443
    volumes:
      # Project files
      - appcode:/var/www/html
      - ${PROJECT_LOCATION}/app/code:/var/www/html/app/code:delegated
      - ${PROJECT_LOCATION}/app/design:/var/www/html/app/design:delegated
      - ${PROJECT_LOCATION}/app/etc:/var/www/html/app/etc:delegated
      - ${PROJECT_LOCATION}/dev/tools/grunt/configs:/var/www/html/dev/tools/grunt/configs:delegated
      - ${PROJECT_LOCATION}/m2-hotfixes:/var/www/html/m2-hotfixes:delegated
      - ${PROJECT_LOCATION}/pub/media:/var/www/html/pub/media
      - ${PROJECT_LOCATION}/var/log:/var/www/html/var/log
      - ${PROJECT_LOCATION}/composer.json:/var/www/html/composer.json:delegated
      - ${PROJECT_LOCATION}/composer.lock:/var/www/html/composer.lock:delegated
      - ${PROJECT_LOCATION}/yarn.lock:/var/www/html/yarn.lock
      # Custom configuration
      - ${PROJECT_LOCATION}/docker/local/nginx.conf:/etc/nginx/conf.d/custom.conf:ro
    tty: true

  php:
    build:
      context: ./php
      target: ${DOCKER_PHP_IMAGE}
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    volumes:
      # Project files
      - appcode:/var/www/html
      - ${PROJECT_LOCATION}/app/code:/var/www/html/app/code:delegated
      - ${PROJECT_LOCATION}/app/design:/var/www/html/app/design:delegated
      - ${PROJECT_LOCATION}/app/etc:/var/www/html/app/etc:delegated
      - ${PROJECT_LOCATION}/dev/tools/grunt/configs:/var/www/html/dev/tools/grunt/configs:delegated
      - ${PROJECT_LOCATION}/m2-hotfixes:/var/www/html/m2-hotfixes:delegated
      - ${PROJECT_LOCATION}/pub/media:/var/www/html/pub/media
      - ${PROJECT_LOCATION}/var/log:/var/www/html/var/log
      - ${PROJECT_LOCATION}/composer.json:/var/www/html/composer.json:delegated
      - ${PROJECT_LOCATION}/composer.lock:/var/www/html/composer.lock:delegated
      - ${PROJECT_LOCATION}/yarn.lock:/var/www/html/yarn.lock
      # Custom configuration
      - ./php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      # SSH keys
      - ~/.ssh:/home/www-data/.ssh:ro
    tty: true

  redis:
    image: redis:3.2-alpine
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    volumes:
      - redis:/data
    tty: true

volumes:
  appcode: {}
  elasticsearch: {}
  mysql: {}
  redis: {}
