version: "3.4"

services:
  blackfire:
    image: blackfire/blackfire
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    depends_on:
      - php

  elasticsearch:
    build: elasticsearch
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  maildev:
    image: djfarrelly/maildev
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    depends_on:
      - php
    ports:
      - 1080:80

  mysql:
    image: mysql:5.7
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    tty: true

  nginx:
    build: nginx
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    ports:
      - 443:443
    volumes:
      - ${PROJECT_LOCATION}:/var/www/html:rw,delegated
      # Custom configuration
      - ${PROJECT_LOCATION}/docker/local/nginx.conf:/etc/nginx/conf.d/custom.conf:ro
    tty: true

  php:
    build:
      context: ./php
      target: ${DOCKER_PHP_IMAGE}
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    volumes:
      - ${PROJECT_LOCATION}:/var/www/html:rw,delegated
      # Custom configuration
      - ./php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      # SSH keys
      - ~/.ssh:/root/.ssh:ro
    tty: true

  redis:
    image: redis:3.2-alpine
    env_file: ${PROJECT_LOCATION}/docker/local/.env
    volumes:
      - redis:/data
    tty: true

volumes:
  elasticsearch: {}
  mysql: {}
  redis: {}
