version: "2.1"

services:
  nginx:
    image: nginx:latest
    env_file: docker-env
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./docker/nginx/servers:/etc/nginx/conf.d"
    volumes_from:
      - php
    tty: true

  php:
    build: php
    env_file: docker-env
    ports:
      - "9000:9000"
    volumes:
      - "./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini"
      - ~/www:/var/www/html
    tty: true

  percona:
    image: percona:latest
    env_file: docker-env
    ports:
      - "3306:3306"
    volumes:
      - "./docker/percona/custom.cnf:/etc/mysql/conf.d/custom.cnf"
      - "mysql:/var/lib/mysql"
    tty: true

  elasticsearch:
    image: elasticsearch:2
    env_file: docker-env
    ports:
      - "9200:9200"
    volumes:
      - "./docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    tty: true

  redis:
    image: redis:latest
    env_file: docker-env
    ports:
      - "6379:6379"
    tty: true

  varnish:
    build: varnish
    env_file: docker-env
    depends_on:
      - nginx
      - php
    ports:
      - "80:8080"
    volumes:
      - "./docker/varnish/default.vcl:/etc/varnish/default.vcl"
    tty: true

volumes:
  mysql: {}
