DOCKER_PATH := ./vendor/emakinafr/docker-magento2
MAKEFILE_DIRECTORY := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

# Retrieve the Makefile used to manage the Docker environment
export COMPOSE_FILE := $(DOCKER_PATH)/docker-compose.yml
include $(DOCKER_PATH)/Makefile
