version: 2

jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    steps:
      - run:
          name: Install system requirements
          command: |
              wget -qO- "https://github.com/havoc-io/mutagen/releases/download/$MUTAGEN_ARCHIVE" | tar xvz -C "$HOME/bin/"
              mutagen daemon start
          environment:
            MUTAGEN_ARCHIVE: v0.8.0/mutagen_linux_amd64_v0.8.0.tar.gz
      - run:
          name: Create a Magento Open Source project
          command: |
              ssh-keyscan github.com >> ~/.ssh/known_hosts
              git clone git@github.com:magento/magento2.git ~/magento
      - run:
          name: Install the Composer dependencies
          command: 'docker run --rm -it -v ~/magento:/app composer install --no-progress --ignore-platform-reqs'
      - run:
          name: Install the Docker environment through Composer
          command: 'docker run --rm -it -v ~/magento:/app composer require emakinafr/docker-magento2:dev-${CIRCLE_BRANCH} --dev --no-progress --ignore-platform-reqs'
      - run:
          name: Execute the post-install process
          command: 'docker run --rm -it -v ~/magento:/app composer exec docker-local-install -vvv'
      - run:
          name: Configure the environment variables
          command: 'sudo cp ~/magento/docker/local/.env.dist ~/magento/docker/local/.env'
      - run:
          name: Start the environment
          command: 'cd ~/magento && make build start ps'
      - run:
          name: Try to access the setup page of Magento 2
          command: |
              while [[ ! $(mutagen list) =~ 'Status: Watching for changes' ]]; do
                echo 'Waiting for synchronization to complete...'
                sleep 10
              done
              curl --insecure --location --resolve "www.magento.localhost:443:127.0.0.1" https://www.magento.localhost/setup/
workflows:
  version: 2
  build:
    jobs:
      - build
