name: "Continuous Integration"

on:
  pull_request:
    branches:
      - master

jobs:
  docker:
    name: "Docker"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: 'magento/magento2'

      - name: "Prepare building context"
        run: |
          ls -la
          #sudo mkdir -p docker/local
          #sudo cp ../.env.dist docker/local/.env

      - name: "Build containers"
        run: |
          #export $(/docker/local/.env | sed 's/#.*//g' | xargs)
          #docker-compose up -d
        env:
          COMPOSE_PROJECT_NAME: magento

      - name: "Display images & containers"
        run: |
          #docker images
          #docker ps
